### PR TITLE
Apply ktlint

### PR DESCRIPTION
**Pull request by tuanchauict**
Changes:
- Apply [ktlint](https://ktlint.github.io/) as a plugin in `build.gradle` via `ktlint.gradle`.
- Apply auto format with the tool (via `./gradlew ktlintFormat`).
- Fix star import in `RetrosheetInterceptor`, `GoogleFormHelper`.
- Update IDE's configuration to prevent star import.
- Rename `Result.kt` -> `Resource.kt` to be the same name with the only class in that file.
- Updare README with `Contributing` section.

### CODE REVIEW

**Comment by theapache64** [comment]
@tuanchauict Great. Can you also update the `README` with a "Contributing" section that explains how to run `ktlintFormat` before making a PR?

**Comment by tuanchauict** [comment]
From here, we can add a new CI as:
```yml
name: ktlint
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: ./gradlew ktlint
```

**Comment by tuanchauict** [comment]
@theapache64 : Done
Btw, could you apply the CI for ktlint then? 
I intended but it doesn't run from this PR, maybe we need to rename the main branch to `main` to align with Github requirement (no `master` branch).

**Comment by theapache64** [comment]
@tuanchauict Yeah, it'll work when I merge this to `master`. Branch naming is not an issue.

**Comment by theapache64** [comment]
@tuanchauict I'll add the CI file.

**Comment by theapache64** [comment]
Done. It works :+1: Good job 

https://github.com/theapache64/retrosheet/pull/14

**Comment by tuanchauict** [comment]
Nice!! 👍

**Pull request merged**
